test: &default

  # Credentials for REST APIs
  client_id: Af43QxK2o4zjNu-ZcvSe_4pWxZbFDxXlhJUbSHpiMqj_V1BDRddhGqAus2UDvrWcU4WHDZ1NnKwzGkFw
  client_secret: ECV9f-LyrjSb6BQWzO_gvritEd71XNQi6qRsl8o3-YusLh4mjoXRmGWH6pnJV-JjEh_hcmXe1E3j-QtV

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: live
